package edu.progAvUD.parcialPrimerCorte.vista;

/**
 *Este panel sirve para poder insertar un nuevo gato a la base de datos
 * @author Andres Felipe
 */
public class PanelInsertarGato extends javax.swing.JPanel {

    /**
     * Creates new form PanelInsertarGato
     */
    public PanelInsertarGato() {
        initComponents();
    }

    /**
     *Este metodo limpia los campos del panel
     */
    public void limpiarCampos() {
        // Restablece JComboBox al primer elemento (índice 0)
        jComboBoxColaGato.setSelectedIndex(0);
        jComboBoxColorGato.setSelectedIndex(0);
        jComboBoxColorOjosGato.setSelectedIndex(0);
        jComboBoxPatronGato.setSelectedIndex(0);
        jComboBoxRazaGato.setSelectedIndex(0);
        jComboBoxCantidadBlanco.setSelectedIndex(0);
        jComboBoxRazaGato.setSelectedIndex(0);

        // Restablece JSpinner al valor inicial (puede ser 0 o cualquier valor predeterminado)
        jSpinnerEdadGato.setValue(0);
        jSpinnerPesoGato.setValue(1);

        // Limpia el JTextField
        jTextFieldNombreGato.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreGato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerPesoGato = new javax.swing.JSpinner();
        jSpinnerEdadGato = new javax.swing.JSpinner();
        jComboBoxRazaGato = new javax.swing.JComboBox<>();
        jComboBoxColorGato = new javax.swing.JComboBox<>();
        jComboBoxPatronGato = new javax.swing.JComboBox<>();
        jComboBoxColorOjosGato = new javax.swing.JComboBox<>();
        jComboBoxColaGato = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonLimpiarCampos = new javax.swing.JButton();
        jButtonInsertarGato = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxCantidadBlanco = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxPuntosColor = new javax.swing.JComboBox<>();

        jLabel1.setText("Nombre del Gato");

        jLabel2.setText("Peso del Gato");

        jLabel3.setText("Edad del Gato");

        jSpinnerPesoGato.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, null, 0.1d));

        jSpinnerEdadGato.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jComboBoxRazaGato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABY-Abyssinian", "AMB-American Burmese", "ACL-American Curl Longhair", "ACS-American Curl Shorthair", "ASH-American Shorthair", "AWH-American Wirehair", "ANA-Anatoli", "APL-Aphrodite’s Giant Longhair", "APS-Aphrodite’s Giant Shorthair", "ARM-Arabian Mau", "ASI-Asian", "AUM-Australian Mist", "BAL-Balinese", "BEN-Bengal", "BOM-Bombay", "BRA-Brazilian Shorthair", "BLH-British Longhair", "BRI-British Shorthair", "BUR-Burmese", "BML-Burmilla Longhair", "BMS-Burmilla Shorthair", "CAM-Cashmere", "KKH-Celtic Shorthair", "CEY-Ceylon", "CHA-Chartreux", "CHS-Chausie", "CRX-Cornish Rex", "CYM-Cymric", "DLH-Deutsch-Langhaar", "DRX-Devon Rex", "DSX-Don Sphynx", "MAU-Egyptian Mau", "EXO-Exotic Shorthair", "GRX-German Rex", "HAV-Havana", "SFL-Highland Fold", "PER-Himalayan / Colourpoint", "HHP-Household Pet", "JBL-Japanese Bobtail Longhair", "JBS-Japanese Bobtail Shorthair", "KAN-Kanaani", "KAL-Karelian Bobtail Longhair", "KAS-Karelian Bobtail Shorthair", "KAM-Khao Manee", "KOR-Korat", "KBL-Kurilian Bobtail Langhaar", "KBS-Kurilian Bobtail Shorthair", "LPL-LaPerm Longhair", "LPS-LaPerm Shorthair", "LYS-Lykoi", "MCO-Maine Coon", "MAN-Manx", "MBT-Mekong Bobtail", "MIL-Minuet Longhair", "MIS-Minuet Shorthair", "MNL-Munchkin Longhair", "MNS-Munchkin Shorthair", "NEB-Nebelung", "NFO-Norwegian Forest", "OCI-Ocicat", "OSL-Oriental Semilonghair", "OSH-Oriental Shorthair", "TLH-Original Longhair", "PER-Persian", "PBD-Peterbald", "RGM-Ragamuffin", "RAG-Ragdoll", "RUS-Russian Blue", "SBI-Sacred Birman", "SFS-Scottish Fold", "SRL-Selkirk Rex Longhair", "SRS-Selkirk Rex Shorthair", "SIA-Siamese", "SIB-Siberian cat / Neva Masquerade", "SIN-Singapura", "SNO-Snowshoe", "SOM-Somali", "SPH-Sphynx", "THA-Thai", "TIF-Tiffanie", "TON-Tonkinese", "TOB-Toy Bob", "TUA-Turkish Angora", "TUV-Turkish Van", "URL-Ural Rex Longhair", "URS-Ural Rex Shorthair", "YOR-York" }));

        jComboBoxColorGato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "n-black", "f-black tortie", "a-blue", "g-blue tortie", "b-chocolate", "h-chocolate tortie", "c-lilac", "o-cinnamon", "q-cinnamon tortie", "d-red", "e-cream", "p-fawn", "r-fawn tortie", "j-lilac tortie", "w-white", "n-seal", "x-unrecognized" }));

        jComboBoxPatronGato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11-shaded", "12-shell", "21-tabby", "21-lynx", "22-classic", "23-mackerel", "24-spotted", "25-ticked", "26-grizzled ticked" }));

        jComboBoxColorOjosGato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "61-blue", "62-orange", "63-odd", "64-green", "65-golden BUR", "66-aquamarine TON", "67-dark Blue SIA" }));

        jComboBoxColaGato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "51-rumpy", "52-rumpy riser", "53-stumpy", "54-longie" }));

        jLabel4.setText("Raza del Gato");

        jLabel5.setText("Color del Gato");

        jLabel6.setText("Patron del Gato");

        jLabel7.setText("Color Ojos del Gato");

        jLabel8.setText("Cola del Gato");

        jButtonLimpiarCampos.setText("Limpiar Campos");

        jButtonInsertarGato.setText("Insertar");

        jButtonAtras.setText("Atras");

        jLabel9.setText("Ingrese los sigientes datos para insertar un Gato");

        jLabel10.setText("Cantidad De Blanco");

        jComboBoxCantidadBlanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01-van ", "02-harlequin ", "03-bicolour ", "04-mitted ", "05-snowshoe ", "09-medaillon" }));

        jLabel11.setText("Puntos de Color");

        jComboBoxPuntosColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "31-sepia", "32-mink", "33-himalayan / siames", "33-no sepia / no mink" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAtras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxRazaGato, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxColorGato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerEdadGato)
                            .addComponent(jSpinnerPesoGato)
                            .addComponent(jTextFieldNombreGato)
                            .addComponent(jComboBoxColorOjosGato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxColaGato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCantidadBlanco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxPatronGato, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxPuntosColor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButtonLimpiarCampos)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonInsertarGato)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNombreGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerPesoGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerEdadGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxRazaGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxColorGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxCantidadBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPatronGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxPuntosColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxColorOjosGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(10, 10, 10)
                        .addComponent(jComboBoxColaGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertarGato)
                    .addComponent(jButtonLimpiarCampos))
                .addGap(14, 14, 14)
                .addComponent(jButtonAtras)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAtras;
    public javax.swing.JButton jButtonInsertarGato;
    public javax.swing.JButton jButtonLimpiarCampos;
    public javax.swing.JComboBox<String> jComboBoxCantidadBlanco;
    public javax.swing.JComboBox<String> jComboBoxColaGato;
    public javax.swing.JComboBox<String> jComboBoxColorGato;
    public javax.swing.JComboBox<String> jComboBoxColorOjosGato;
    public javax.swing.JComboBox<String> jComboBoxPatronGato;
    public javax.swing.JComboBox<String> jComboBoxPuntosColor;
    public javax.swing.JComboBox<String> jComboBoxRazaGato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JSpinner jSpinnerEdadGato;
    public javax.swing.JSpinner jSpinnerPesoGato;
    public javax.swing.JTextField jTextFieldNombreGato;
    // End of variables declaration//GEN-END:variables
}
