/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.progAvUD.parcialPrimerCorte.vista;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres Felipe
 */
public class PanelConsultarGato extends javax.swing.JPanel {

    public DialogInformacionGato dialogInformacionGato;

    /**
     * Creates new form PanelConsultarGato
     */
    public PanelConsultarGato() {
        initComponents();
    }

    public void crearDialog(JFrame frame) {
        this.dialogInformacionGato = new DialogInformacionGato(frame, "Datos gatos", true);
        dialogInformacionGato.setLocationRelativeTo(frame);
    }

    public void limpiarCampos() {
        buttonGroupTipoConsulta.clearSelection();
        // Reiniciar selección del combo box
        jComboBoxRaza.setSelectedIndex(0);
        // Limpiar campo de texto
        jTextFieldCodigoEMS.setText("");
        // Limpiar tabla
        modeloTablaGatos.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoConsulta = new javax.swing.ButtonGroup();
        jButtonAtras = new javax.swing.JButton();
        jRadioButtonRaza = new javax.swing.JRadioButton();
        jRadioButtonCodigoEMS = new javax.swing.JRadioButton();
        jComboBoxRaza = new javax.swing.JComboBox<>();
        jScrollPaneTablaGatos = new javax.swing.JScrollPane();
        jTableGatos = new javax.swing.JTable();
        jButtonConsultar = new javax.swing.JButton();
        jButtonLimpiarCampos = new javax.swing.JButton();
        jTextFieldCodigoEMS = new javax.swing.JTextField();
        jButtonInfoGato = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelTextoRaza = new javax.swing.JLabel();
        jLabelTextoCodigoEMS = new javax.swing.JLabel();

        jButtonAtras.setText("Atras");

        buttonGroupTipoConsulta.add(jRadioButtonRaza);
        jRadioButtonRaza.setText("Nombre de Raza");

        buttonGroupTipoConsulta.add(jRadioButtonCodigoEMS);
        jRadioButtonCodigoEMS.setText("Codigo EMS");

        jComboBoxRaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABY-Abyssinian", "AMB-American Burmese", "ACL-American Curl Longhair", "ACS-American Curl Shorthair", "ASH-American Shorthair", "AWH-American Wirehair", "ANA-Anatoli", "APL-Aphrodite’s Giant Longhair", "APS-Aphrodite’s Giant Shorthair", "ARM-Arabian Mau", "ASI-Asian", "AUM-Australian Mist", "BAL-Balinese", "BEN-Bengal", "BOM-Bombay", "BRA-Brazilian Shorthair", "BLH-British Longhair", "BRI-British Shorthair", "BUR-Burmese", "BML-Burmilla Longhair", "BMS-Burmilla Shorthair", "CAM-Cashmere", "KKH-Celtic Shorthair", "CEY-Ceylon", "CHA-Chartreux", "CHS-Chausie", "CRX-Cornish Rex", "CYM-Cymric", "DLH-Deutsch-Langhaar", "DRX-Devon Rex", "DSX-Don Sphynx", "MAU-Egyptian Mau", "EXO-Exotic Shorthair", "GRX-German Rex", "HAV-Havana", "SFL-Highland Fold", "PER-Himalayan / Colourpoint", "HHP-Household Pet", "JBL-Japanese Bobtail Longhair", "JBS-Japanese Bobtail Shorthair", "KAN-Kanaani", "KAL-Karelian Bobtail Longhair", "KAS-Karelian Bobtail Shorthair", "KAM-Khao Manee", "KOR-Korat", "KBL-Kurilian Bobtail Langhaar", "KBS-Kurilian Bobtail Shorthair", "LPL-LaPerm Longhair", "LPS-LaPerm Shorthair", "LYS-Lykoi", "MCO-Maine Coon", "MAN-Manx", "MBT-Mekong Bobtail", "MIL-Minuet Longhair", "MIS-Minuet Shorthair", "MNL-Munchkin Longhair", "MNS-Munchkin Shorthair", "NEB-Nebelung", "NFO-Norwegian Forest", "OCI-Ocicat", "OSL-Oriental Semilonghair", "OSH-Oriental Shorthair", "TLH-Original Longhair", "PER-Persian", "PBD-Peterbald", "RGM-Ragamuffin", "RAG-Ragdoll", "RUS-Russian Blue", "SBI-Sacred Birman", "SFS-Scottish Fold", "SRL-Selkirk Rex Longhair", "SRS-Selkirk Rex Shorthair", "SIA-Siamese", "SIB-Siberian cat / Neva Masquerade", "SIN-Singapura", "SNO-Snowshoe", "SOM-Somali", "SPH-Sphynx", "THA-Thai", "TIF-Tiffanie", "TON-Tonkinese", "TOB-Toy Bob", "TUA-Turkish Angora", "TUV-Turkish Van", "URL-Ural Rex Longhair", "URS-Ural Rex Shorthair", "YOR-York" }));

        modeloTablaGatos= new DefaultTableModel(new Object[]{ "ID Gato", "Nombre Gato","CodigoEMS Gato"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTableGatos.setModel(modeloTablaGatos);
        jScrollPaneTablaGatos.setViewportView(jTableGatos);

        jButtonConsultar.setText("Consultar");

        jButtonLimpiarCampos.setText("Limpiar Campos");

        jButtonInfoGato.setText("Ver Informacion del Gato");

        jLabel1.setText("Seleccione el parametro que decea utilizar para la consulta");

        jLabelTextoRaza.setText("Selecciona la Raza");

        jLabelTextoCodigoEMS.setText("Escriba el Codigo EMS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jButtonLimpiarCampos)
                .addGap(27, 27, 27)
                .addComponent(jButtonConsultar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAtras)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPaneTablaGatos, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTextoRaza)
                                            .addComponent(jLabelTextoCodigoEMS))
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCodigoEMS, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(82, 82, 82))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonInfoGato)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jRadioButtonRaza)
                .addGap(59, 59, 59)
                .addComponent(jRadioButtonCodigoEMS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRaza)
                    .addComponent(jRadioButtonCodigoEMS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTextoRaza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoEMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTextoCodigoEMS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultar)
                    .addComponent(jButtonLimpiarCampos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneTablaGatos, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInfoGato)
                .addGap(12, 12, 12)
                .addComponent(jButtonAtras)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipoConsulta;
    public javax.swing.JButton jButtonAtras;
    public javax.swing.JButton jButtonConsultar;
    public javax.swing.JButton jButtonInfoGato;
    public javax.swing.JButton jButtonLimpiarCampos;
    public javax.swing.JComboBox<String> jComboBoxRaza;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelTextoCodigoEMS;
    public javax.swing.JLabel jLabelTextoRaza;
    public javax.swing.JRadioButton jRadioButtonCodigoEMS;
    public javax.swing.JRadioButton jRadioButtonRaza;
    public javax.swing.JScrollPane jScrollPaneTablaGatos;
    public DefaultTableModel modeloTablaGatos;
    public javax.swing.JTable jTableGatos;
    public javax.swing.JTextField jTextFieldCodigoEMS;
    // End of variables declaration//GEN-END:variables
}
