package edu.progAvUD.parcialPrimerCorte.vista;

import java.awt.Dimension;
import java.io.File;

import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import edu.progAvUD.parcialPrimerCorte.control.ControlGrafico;

/**
 *
 * @author Andres Felipe
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControlGrafico controlGrafico;
    public PanelPrincipal panelPrincipal;
    public PanelOpcionesCRUD panelOpcionesCRUD;
    public PanelConsultarGato panelConsultarGato;
    public PanelEliminarGato panelEliminarGato;
    public PanelInsertarGato panelInsertarGato;
    public PanelModificarGato panelModificarGato;
    public PanelMostrarGatos panelMostrarGatos;

    /**
     * Creates new form VentanaPrincipal
     *
     * @param controlGrafico
     */
    public VentanaPrincipal(ControlGrafico controlGrafico) {
        this.controlGrafico = controlGrafico;
        initComponents();
        setVisible(true);
        this.panelPrincipal = new PanelPrincipal();
        this.panelOpcionesCRUD = new PanelOpcionesCRUD();
        this.panelConsultarGato = new PanelConsultarGato();
        this.panelEliminarGato = new PanelEliminarGato(this);
        this.panelInsertarGato = new PanelInsertarGato();
        this.panelModificarGato = new PanelModificarGato(this);
        this.panelMostrarGatos = new PanelMostrarGatos();
    }

    public void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public File pedirArchivoPropiedades() {
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.dir") + "/src/main/java/edu/progAvUD/parcialPrimerCorte/data");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos .properties", "properties"));
        fileChooser.showOpenDialog(null);
        return fileChooser.getSelectedFile();
    }

    public File pedirDirectorioArchivoAleatorio() {
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.dir") + "/src/main/java/edu/progAvUD/parcialPrimerCorte/data");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setDialogTitle("Selecciona un directorio");
        fileChooser.showOpenDialog(null);
        return fileChooser.getSelectedFile();
    }

    /**
     * Se encarga de mostrar cada panel
     *
     * @param panel
     */
    public void mostrarPanel(JPanel panel) {
        setContentPane(panel);
        pack(); // Ajusta el tamaño de la ventana según el contenido
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        revalidate();
        repaint();
    }

    public Object mostrarJOptionSeleccionarDatoFaltante(String datoFaltante, Object[] opciones) {
        String mensaje = "Hace falta el dato de '" + datoFaltante + "'.\nSeleccione una opcion:";
        Object seleccion = JOptionPane.showInputDialog(null,
                mensaje, "Dato Faltante",
                JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        return seleccion;
    }

    public String mostrarJOptionEscribirDatoFaltante(String datoFaltante) {
        String dato = JOptionPane.showInputDialog(null,
                "Hace falta el dato de '" + datoFaltante + "'.\n Escriba el dato:", "Dato Faltante",
                JOptionPane.QUESTION_MESSAGE);
        return dato;
    }

    public String pedirNombreArchivo() {
        JTextField txtNombre = new JTextField(20);
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.add(new JLabel("Digite el nombre del archivo:"));
        panel.add(Box.createRigidArea(new Dimension(0, 5)));
        panel.add(txtNombre);

        int opcion = JOptionPane.showConfirmDialog(
                null,
                panel,
                "Nombre de archivo",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );
        return txtNombre.getText().trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSerializar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Salir");

        jMenuItemSalir.setText("Salir");
        jMenu1.add(jMenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Serializar Base de Datos");

        jMenuItemSerializar.setText("Serializar");
        jMenu2.add(jMenuItemSerializar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemSalir;
    public javax.swing.JMenuItem jMenuItemSerializar;
    // End of variables declaration//GEN-END:variables
}
